// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/with0p/golang-url-shortener.git/internal/service (interfaces: Service)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	commontypes "github.com/with0p/golang-url-shortener.git/internal/common-types"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetTrueURL mocks base method.
func (m *MockService) GetTrueURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrueURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrueURL indicates an expected call of GetTrueURL.
func (mr *MockServiceMockRecorder) GetTrueURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrueURL", reflect.TypeOf((*MockService)(nil).GetTrueURL), arg0, arg1)
}

// MakeShortURL mocks base method.
func (m *MockService) MakeShortURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeShortURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeShortURL indicates an expected call of MakeShortURL.
func (mr *MockServiceMockRecorder) MakeShortURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeShortURL", reflect.TypeOf((*MockService)(nil).MakeShortURL), arg0, arg1)
}

// MakeShortURLBatch mocks base method.
func (m *MockService) MakeShortURLBatch(arg0 context.Context, arg1 []commontypes.RecordToBatch) ([]commontypes.BatchRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeShortURLBatch", arg0, arg1)
	ret0, _ := ret[0].([]commontypes.BatchRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeShortURLBatch indicates an expected call of MakeShortURLBatch.
func (mr *MockServiceMockRecorder) MakeShortURLBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeShortURLBatch", reflect.TypeOf((*MockService)(nil).MakeShortURLBatch), arg0, arg1)
}
